import JSZip from "jszip"

import { buildDesignTokens, designTokensToRootCss } from "@/lib/design/buildDesignTokens"
import type { DesignConfig } from "@/types/designEngine"
import type { PortfolioDocument } from "@/types/dossier"

const README = `# Exported portfolio

This bundle was generated by **Dossier**.

## Contents

- \`data/portfolio.json\` — portfolio content (sections, meta)
- \`data/design-config.json\` — layout + variant plan from the design engine
- \`styles/tokens.css\` — CSS variables (colors, spacing, motion) used by the canvas
- \`app/page.tsx\` — minimal Next.js page that loads the JSON and renders semantic HTML

## Run

\`\`\`bash
npm install
npm run dev
\`\`\`

Copy your own components into \`components/sections/\` and map \`design-config.json\` variants to React implementations for a full Aceternity-style rebuild.
`

function pageTsx(): string {
  return `'use client'

import portfolio from '../data/portfolio.json'
import designConfig from '../data/design-config.json'

export default function Page() {
  const doc = portfolio as typeof portfolio
  const cfg = designConfig as typeof designConfig
  return (
    <main className="min-h-screen bg-[var(--de-bg)] px-6 py-16 text-[var(--de-fg)]">
      <h1 className="text-3xl font-semibold">{doc.meta.title}</h1>
      <p className="mt-2 max-w-2xl text-sm text-[var(--de-muted)]">{doc.meta.description}</p>
      <p className="mt-8 text-xs uppercase tracking-widest text-[var(--de-muted)]">Layout: {cfg.layout}</p>
      <pre className="mt-6 max-h-[50vh] overflow-auto rounded-lg border border-[var(--de-border)] bg-[var(--de-elevated)] p-4 text-xs">
        {JSON.stringify({ portfolio: doc, designConfig: cfg }, null, 2)}
      </pre>
    </main>
  )
}
`
}

function packageJson(): string {
  return JSON.stringify(
    {
      name: "dossier-exported-portfolio",
      version: "0.1.0",
      private: true,
      scripts: {
        dev: "next dev",
        build: "next build",
        start: "next start",
      },
      dependencies: {
        next: "16.2.4",
        react: "19.2.4",
        "react-dom": "19.2.4",
      },
      devDependencies: {
        "@tailwindcss/postcss": "^4",
        postcss: "^8.5.1",
        tailwindcss: "^4",
        typescript: "^5",
      },
    },
    null,
    2
  )
}

function tailwindConfig(): string {
  return `/** @type {import('tailwindcss').Config} */
export default {
  content: ["./app/**/*.{ts,tsx}"],
  theme: { extend: {} },
}
`
}

function postcssConfig(): string {
  return `export default { plugins: { "@tailwindcss/postcss": {} } }
`
}

function nextConfig(): string {
  return `/** @type {import('next').NextConfig} */
const nextConfig = { reactStrictMode: true }
export default nextConfig
`
}

function globalsCss(): string {
  return `@import "tailwindcss";
@import "../styles/tokens.css";

body { font-family: ui-sans-serif, system-ui, sans-serif; }
`
}

function layoutTsx(): string {
  return `import "./globals.css"
import type { Metadata } from "next"

export const metadata: Metadata = { title: "Portfolio export" }

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
`
}

function tsconfig(): string {
  return JSON.stringify(
    {
      compilerOptions: {
        target: "ES2017",
        lib: ["dom", "dom.iterable", "esnext"],
        allowJs: true,
        skipLibCheck: true,
        strict: true,
        noEmit: true,
        module: "esnext",
        moduleResolution: "bundler",
        resolveJsonModule: true,
        isolatedModules: true,
        jsx: "react-jsx",
        incremental: true,
        plugins: [{ name: "next" }],
      },
      include: ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
      exclude: ["node_modules"],
    },
    null,
    2
  )
}

export async function buildPortfolioExportZip(input: {
  document: PortfolioDocument
  designConfig: DesignConfig
  variationSeed: number
}): Promise<Blob> {
  const tokens = buildDesignTokens(input.designConfig, input.variationSeed)
  const zip = new JSZip()

  zip.file("README.md", README)
  zip.file("data/portfolio.json", JSON.stringify(input.document, null, 2))
  zip.file("data/design-config.json", JSON.stringify(input.designConfig, null, 2))
  zip.file("styles/tokens.css", designTokensToRootCss(tokens))
  zip.file("app/layout.tsx", layoutTsx())
  zip.file("app/globals.css", globalsCss())
  zip.file("app/page.tsx", pageTsx())
  zip.file("package.json", packageJson())
  zip.file("tailwind.config.js", tailwindConfig())
  zip.file("postcss.config.js", postcssConfig())
  zip.file("next.config.mjs", nextConfig())
  zip.file("tsconfig.json", tsconfig())

  return zip.generateAsync({ type: "blob" })
}
