import type { PaletteInput, TemplateSpec } from "./types"

/**
 * Curated template catalogue. Variant ids are exact ids from
 * src/components/portfolio/sections/registry.tsx (VARIANT_IDS); /dev/templates flags unknown ids.
 *
 *  hero          : statement | banner | centered | split | card | terminal
 *  about         : prose | lead | columns
 *  skills        : chips | columns | inline
 *  experience    : timeline | rows | cards | list
 *  projects      : cards | feature | list | gallery
 *  contact       : statement | footer | card | list
 *  education     : list | cards
 *  highlights    : figures | list      (real numbers only; hidden when absent)
 *  certifications: list | grid
 *
 * order lists every type; missing sections are skipped and contact always closes the page.
 * Motion preset -> signature: fade-up/stagger-grid = rise, slide-reveal = clip, parallax = clip + cover drift,
 * magnetic = wipe (brutalist).
 */

const p = (bg: string, bg2: string, text: string, muted: string, primary: string, accent: string): PaletteInput => ({
  bg,
  bg2,
  text,
  muted,
  primary,
  accent,
})

export const TEMPLATE_SPECS: readonly TemplateSpec[] = [
  {
    id: "terminal",
    name: "Terminal",
    tagline: "Dark, mono-set, built for people who ship code.",
    bestFor: ["Software developers", "Full-stack and backend", "Open-source contributors", "DevOps / SRE"],
    tones: ["techy", "calm"],
    mode: "dark",
    layout: "split-fixed",
    direction: "LUMINOUS_DARK",
    hero: "terminal",
    heroSection: "terminal",
    nav: "side-rail",
    bgType: "CLEAN_DARK",
    order: ["hero", "about", "highlights", "projects", "experience", "skills", "education", "certifications", "contact"],
    variants: {
      about: "prose",
      skills: "chips",
      experience: "timeline",
      projects: "cards",
      contact: "list",
      education: "list",
      highlights: "list",
      certifications: "list",
    },
    components: { card: "bordered", button: "outline-glow", badge: "square-mono", divider: "none" },
    motion: { preset: "fade-up", stagger: 0.05, y: 20 },
    fonts: { display: "JetBrains Mono", body: "IBM Plex Sans", mono: "JetBrains Mono", displayWeight: 700, headingWeight: 600, tracking: "-0.03em", leading: 1.08, label: "0.16em" },
    radius: "rounded-lg",
    density: "normal",
    glow: false,
    heroTiers: [0, 1],
    palettes: [
      p("#0C1117", "#131A22", "#E6EDF3", "#8FA1B3", "#5FD3B8", "#E3B341"),
      p("#0C1117", "#131A22", "#E6EDF3", "#8FA1B3", "#7AA2F7", "#F7768E"),
      p("#0C1117", "#131A22", "#E6EDF3", "#8FA1B3", "#B8E55A", "#66D9EF"),
    ],
    match: { clusters: ["software"], secondary: ["engineering"], personality: ["technical"], emphasis: "projects", projectLed: true },
  },
  {
    id: "plain",
    name: "Plain Text",
    tagline: "Quiet, typographic, almost no decoration.",
    bestFor: ["Developers who prefer minimal", "Senior engineers", "Technical writers", "Data and ML engineers"],
    tones: ["calm", "formal", "techy"],
    mode: "light",
    layout: "single-column",
    direction: "EDITORIAL_MONO",
    hero: "editorial",
    heroSection: "statement",
    nav: "full-width-bar",
    bgType: "EDITORIAL_FLAT",
    order: ["hero", "about", "highlights", "projects", "experience", "skills", "education", "certifications", "contact"],
    variants: {
      about: "prose",
      skills: "inline",
      experience: "list",
      projects: "list",
      contact: "statement",
      education: "list",
      highlights: "list",
      certifications: "list",
    },
    components: { card: "flat", button: "text-arrow", badge: "outlined", divider: "thick-ruled" },
    motion: { preset: "fade-up", stagger: 0.04, y: 20 },
    fonts: { display: "Schibsted Grotesk", body: "Source Sans 3", mono: "IBM Plex Mono", displayWeight: 700, headingWeight: 700, tracking: "-0.035em", leading: 1.02, label: "0.18em" },
    radius: "rounded-none",
    density: "normal",
    glow: false,
    heroTiers: [1, 2],
    palettes: [
      p("#FAFAF7", "#F0F0EA", "#16181D", "#5A5F6A", "#2342C9", "#D9480F"),
      p("#FAFAF7", "#F0F0EA", "#16181D", "#5A5F6A", "#0B7A5B", "#B45309"),
      p("#FAFAF7", "#F0F0EA", "#16181D", "#5A5F6A", "#8B2F3C", "#0E7490"),
    ],
    match: { clusters: ["software"], secondary: ["engineering", "design", "unknown"], personality: ["technical", "academic"], emphasis: "experience", seniority: ["senior", "lead"] },
  },
  {
    id: "nocturne",
    name: "Nocturne",
    tagline: "Charcoal and one warm accent, for builders who care about the details.",
    bestFor: ["Creative developers", "Front-end and WebGL", "Indie hackers", "Game and interactive devs"],
    tones: ["bold", "playful", "techy"],
    mode: "dark",
    layout: "asymmetric",
    direction: "LUMINOUS_DARK",
    hero: "kinetic",
    heroSection: "banner",
    nav: "floating-pill",
    bgType: "CLEAN_DARK",
    order: ["hero", "projects", "highlights", "about", "experience", "skills", "education", "certifications", "contact"],
    variants: {
      about: "columns",
      skills: "chips",
      experience: "cards",
      projects: "feature",
      contact: "footer",
      education: "list",
      highlights: "figures",
      certifications: "list",
    },
    components: { card: "bordered", button: "solid", badge: "outlined", divider: "none" },
    motion: { preset: "slide-reveal", stagger: 0.06, y: 28 },
    fonts: { display: "Syne", body: "DM Sans", mono: "Fira Code", displayWeight: 700, headingWeight: 700, tracking: "-0.035em", leading: 1.0, label: "0.18em" },
    radius: "rounded-lg",
    density: "airy",
    glow: false,
    heroTiers: [1, 2],
    palettes: [
      p("#0F1115", "#171A20", "#ECEAE4", "#A3A09A", "#F2A65A", "#7DB7A8"),
      p("#0E1412", "#151D1A", "#E8EFEA", "#9DB0A6", "#7FD1A8", "#E9C46A"),
      p("#12100F", "#1B1816", "#F1ECE6", "#B0A69C", "#FF8A65", "#8FB8DE"),
    ],
    match: { clusters: ["software", "creative"], secondary: ["design"], personality: ["creative", "technical"], emphasis: "projects", projectLed: true, needsRich: true },
  },
  {
    id: "studio",
    name: "Studio",
    tagline: "Warm paper, big type and a gallery of work.",
    bestFor: ["UI / UX designers", "Product and brand designers", "Illustrators", "Motion designers"],
    tones: ["bold", "playful", "warm"],
    mode: "light",
    layout: "magazine",
    direction: "ORGANIC_GRADIENT",
    hero: "editorial",
    heroSection: "banner",
    nav: "floating-pill",
    bgType: "EDITORIAL_FLAT",
    order: ["hero", "projects", "about", "highlights", "experience", "skills", "education", "certifications", "contact"],
    variants: {
      about: "lead",
      skills: "inline",
      experience: "rows",
      projects: "gallery",
      contact: "footer",
      education: "list",
      highlights: "figures",
      certifications: "list",
    },
    components: { card: "bordered", button: "solid", badge: "outlined", divider: "none" },
    motion: { preset: "parallax", stagger: 0.07, y: 40 },
    fonts: { display: "Bricolage Grotesque", body: "Hanken Grotesk", mono: "DM Mono", displayWeight: 700, headingWeight: 700, tracking: "-0.04em", leading: 1.0, label: "0.2em" },
    radius: "rounded-2xl",
    density: "airy",
    glow: false,
    heroTiers: [1, 2],
    palettes: [
      p("#F7F3EE", "#EEE7DE", "#1D1A17", "#5E564E", "#B23A0A", "#1D4ED8"),
      p("#F7F3EE", "#EEE7DE", "#1D1A17", "#5E564E", "#1D4ED8", "#B23A0A"),
      p("#F7F3EE", "#EEE7DE", "#1D1A17", "#5E564E", "#0D6E66", "#C2410C"),
    ],
    match: { clusters: ["design"], secondary: ["creative", "marketing"], emphasis: "projects", projectLed: true, designy: true, needsRich: true, personality: ["creative"] },
  },
  {
    id: "atelier",
    name: "Atelier",
    tagline: "A dark gallery wall for visual and written work.",
    bestFor: ["Artists and photographers", "Writers and editors", "Filmmakers", "Illustrators with a portfolio"],
    tones: ["calm", "bold", "warm"],
    mode: "dark",
    layout: "asymmetric",
    direction: "ORGANIC_GRADIENT",
    hero: "split-left",
    heroSection: "split",
    nav: "floating-pill",
    bgType: "EDITORIAL_FLAT",
    order: ["hero", "projects", "about", "experience", "highlights", "education", "skills", "certifications", "contact"],
    variants: {
      about: "lead",
      skills: "inline",
      experience: "list",
      projects: "gallery",
      contact: "statement",
      education: "list",
      highlights: "list",
      certifications: "list",
    },
    components: { card: "bordered", button: "text-arrow", badge: "outlined", divider: "none" },
    motion: { preset: "parallax", stagger: 0.08, y: 36 },
    fonts: { display: "Source Serif 4", body: "Albert Sans", mono: "DM Mono", displayWeight: 600, headingWeight: 600, tracking: "-0.025em", leading: 1.02, label: "0.22em" },
    radius: "rounded-lg",
    density: "airy",
    glow: false,
    heroTiers: [1, 2],
    palettes: [
      p("#141210", "#1C1916", "#F2EBDD", "#A89F90", "#E8B77B", "#D97B66"),
      p("#111514", "#181E1C", "#E9F0EC", "#9AAAA2", "#A8D5BA", "#E6C07B"),
      p("#101419", "#171D24", "#EDEFF2", "#9FA9B5", "#8FC1E3", "#E8B77B"),
    ],
    match: { clusters: ["creative"], secondary: ["design", "culinary"], personality: ["creative"], emphasis: "projects", projectLed: true, designy: true, needsRich: true },
  },
  {
    id: "fresh-start",
    name: "Fresh Start",
    tagline: "Bright and friendly: projects and skills lead.",
    bestFor: ["Students and fresh graduates", "Bootcamp alumni", "Interns", "Junior developers and designers"],
    tones: ["playful", "warm", "calm"],
    mode: "light",
    layout: "single-column",
    direction: "LIQUID_ENTERPRISE",
    hero: "split-left",
    heroSection: "card",
    nav: "floating-pill",
    bgType: "EDITORIAL_FLAT",
    order: ["hero", "about", "education", "projects", "skills", "experience", "certifications", "highlights", "contact"],
    variants: {
      about: "prose",
      skills: "chips",
      experience: "timeline",
      projects: "cards",
      contact: "card",
      education: "cards",
      highlights: "figures",
      certifications: "grid",
    },
    components: { card: "solid", button: "solid", badge: "pill-glass", divider: "none" },
    motion: { preset: "stagger-grid", stagger: 0.06, y: 32 },
    fonts: { display: "Gabarito", body: "Nunito Sans", mono: "Fira Code", displayWeight: 700, headingWeight: 700, tracking: "-0.03em", leading: 1.04, label: "0.16em" },
    radius: "rounded-2xl",
    density: "normal",
    glow: false,
    heroTiers: [1],
    palettes: [
      p("#F5FAFF", "#E8F1FB", "#0F1B2D", "#4A5B73", "#1456D9", "#E8590C"),
      p("#F4FBF7", "#E5F4EC", "#0F2A1F", "#46605A", "#0B7A52", "#E8590C"),
      p("#FFF8F1", "#FDEBDC", "#2A1A0F", "#6B5444", "#B83B08", "#1456D9"),
    ],
    match: { clusters: ["student"], secondary: ["software", "design", "marketing"], seniority: ["student", "junior"], stage: ["building"], emphasis: "projects", projectLed: true },
  },
  {
    id: "essential",
    name: "Essential",
    tagline: "Calm, generous spacing that makes a short resume feel complete.",
    bestFor: ["Short or one-page resumes", "Early career with little experience", "Anyone wanting a clean one-pager", "First-time portfolios"],
    tones: ["calm", "warm"],
    mode: "light",
    layout: "single-column",
    direction: "LIQUID_ENTERPRISE",
    hero: "fullscreen-center",
    heroSection: "centered",
    nav: "none",
    bgType: "EDITORIAL_FLAT",
    order: ["hero", "about", "highlights", "experience", "education", "skills", "projects", "certifications", "contact"],
    variants: {
      about: "prose",
      skills: "chips",
      experience: "timeline",
      projects: "list",
      contact: "card",
      education: "list",
      highlights: "list",
      certifications: "list",
    },
    components: { card: "solid", button: "solid", badge: "outlined", divider: "none" },
    motion: { preset: "fade-up", stagger: 0.05, y: 24 },
    fonts: { display: "Manrope", body: "Public Sans", mono: "IBM Plex Mono", displayWeight: 700, headingWeight: 700, tracking: "-0.03em", leading: 1.06, label: "0.18em" },
    radius: "rounded-2xl",
    density: "airy",
    glow: false,
    heroTiers: [1],
    palettes: [
      p("#FBFAF8", "#F2EFEA", "#1B1B1D", "#5B5A5F", "#2F5D50", "#B7791F"),
      p("#FBFAF8", "#F2EFEA", "#1B1B1D", "#5B5A5F", "#8A3B2E", "#4A6FA5"),
      p("#FBFAF8", "#F2EFEA", "#1B1B1D", "#5B5A5F", "#3B4CCA", "#B45309"),
    ],
    match: { clusters: ["sparse"], richness: ["sparse"], emphasis: "experience", base: 9 },
  },
  {
    id: "classic",
    name: "Classic",
    tagline: "A dependable sidebar layout that suits almost any profession.",
    bestFor: ["Any profession", "Resumes that do not fit a niche", "Mid-career generalists", "Operations and admin"],
    tones: ["formal", "calm"],
    mode: "light",
    layout: "split-fixed",
    direction: "LIQUID_ENTERPRISE",
    hero: "fullscreen-center",
    heroSection: "statement",
    nav: "side-rail",
    bgType: "ENTERPRISE_GRADIENT",
    order: ["hero", "about", "highlights", "experience", "skills", "education", "certifications", "projects", "contact"],
    variants: {
      about: "columns",
      skills: "columns",
      experience: "rows",
      projects: "cards",
      contact: "list",
      education: "list",
      highlights: "figures",
      certifications: "list",
    },
    components: { card: "solid", button: "solid", badge: "outlined", divider: "none" },
    motion: { preset: "fade-up", stagger: 0.05, y: 24 },
    fonts: { display: "Work Sans", body: "Work Sans", mono: "IBM Plex Mono", displayWeight: 700, headingWeight: 600, tracking: "-0.03em", leading: 1.05, label: "0.16em" },
    radius: "rounded-lg",
    density: "normal",
    glow: false,
    heroTiers: [0, 1],
    palettes: [
      p("#FFFFFF", "#F3F6FA", "#111827", "#4B5563", "#1D4ED8", "#0E7490"),
      p("#FFFFFF", "#F3F6FA", "#111827", "#4B5563", "#0F5C4D", "#9A3412"),
      p("#FFFFFF", "#F3F6FA", "#111827", "#4B5563", "#8A2D3B", "#0E7490"),
    ],
    match: { clusters: ["unknown"], emphasis: "experience", base: 14 },
  },
  {
    id: "ledger",
    name: "Ledger",
    tagline: "Navy and brass: credentials, metrics and a steady hand.",
    bestFor: ["Accountants and auditors", "Finance and banking", "Analysts and controllers", "Tax and compliance"],
    tones: ["formal", "calm"],
    mode: "light",
    layout: "single-column",
    direction: "LIQUID_ENTERPRISE",
    hero: "fullscreen-center",
    heroSection: "centered",
    nav: "full-width-bar",
    bgType: "ENTERPRISE_GRADIENT",
    order: ["hero", "highlights", "about", "experience", "certifications", "education", "skills", "projects", "contact"],
    variants: {
      about: "columns",
      skills: "columns",
      experience: "rows",
      projects: "list",
      contact: "list",
      education: "list",
      highlights: "figures",
      certifications: "grid",
    },
    components: { card: "solid", button: "solid", badge: "outlined", divider: "none" },
    motion: { preset: "fade-up", stagger: 0.04, y: 20 },
    fonts: { display: "IBM Plex Serif", body: "IBM Plex Sans", mono: "IBM Plex Mono", displayWeight: 600, headingWeight: 600, tracking: "-0.02em", leading: 1.08, label: "0.14em" },
    radius: "rounded-lg",
    density: "normal",
    glow: false,
    heroTiers: [0, 1],
    palettes: [
      p("#F8F9FB", "#EDF0F5", "#101828", "#475467", "#1B3A63", "#A16207"),
      p("#F8F9FB", "#EDF0F5", "#101828", "#475467", "#0F4C45", "#A16207"),
      p("#F8F9FB", "#EDF0F5", "#101828", "#475467", "#2B4C7E", "#B45309"),
    ],
    match: { clusters: ["finance"], secondary: ["legal", "hr", "sales"], personality: ["corporate"], emphasis: "credentials", seniority: ["mid", "senior", "lead"] },
  },
  {
    id: "chalk",
    name: "Chalkboard",
    tagline: "Warm, legible and human: about and experience first.",
    bestFor: ["Teachers and tutors", "Trainers and instructional designers", "School leaders", "Education support staff"],
    tones: ["warm", "calm", "playful"],
    mode: "light",
    layout: "single-column",
    direction: "LIQUID_ENTERPRISE",
    hero: "split-left",
    heroSection: "card",
    nav: "full-width-bar",
    bgType: "EDITORIAL_FLAT",
    order: ["hero", "about", "experience", "education", "certifications", "skills", "highlights", "projects", "contact"],
    variants: {
      about: "lead",
      skills: "columns",
      experience: "timeline",
      projects: "cards",
      contact: "card",
      education: "cards",
      highlights: "list",
      certifications: "list",
    },
    components: { card: "solid", button: "solid", badge: "pill-glass", divider: "none" },
    motion: { preset: "stagger-grid", stagger: 0.05, y: 24 },
    fonts: { display: "Literata", body: "Nunito Sans", mono: "Source Code Pro", displayWeight: 600, headingWeight: 600, tracking: "-0.02em", leading: 1.08, label: "0.14em" },
    radius: "rounded-2xl",
    density: "normal",
    glow: false,
    heroTiers: [0, 1],
    palettes: [
      p("#FBF8F1", "#F1ECDF", "#232B24", "#556056", "#2F6B4F", "#C2410C"),
      p("#FBF8F1", "#F1ECDF", "#232B24", "#556056", "#1E5A8A", "#B45309"),
      p("#FBF8F1", "#F1ECDF", "#232B24", "#556056", "#8B3A62", "#2F6B4F"),
    ],
    match: { clusters: ["education"], secondary: ["hr", "healthcare"], emphasis: "experience", personality: ["academic"] },
  },
  {
    id: "clinic",
    name: "Clinic",
    tagline: "Clear, reassuring and easy on the eyes. Credentials up front.",
    bestFor: ["Nurses and clinicians", "Allied health professionals", "Pharmacists and lab staff", "Healthcare administrators"],
    tones: ["calm", "warm", "formal"],
    mode: "light",
    layout: "single-column",
    direction: "LIQUID_ENTERPRISE",
    hero: "fullscreen-center",
    heroSection: "centered",
    nav: "full-width-bar",
    bgType: "EDITORIAL_FLAT",
    order: ["hero", "about", "certifications", "experience", "education", "skills", "highlights", "projects", "contact"],
    variants: {
      about: "prose",
      skills: "columns",
      experience: "timeline",
      projects: "list",
      contact: "list",
      education: "list",
      highlights: "list",
      certifications: "grid",
    },
    components: { card: "solid", button: "solid", badge: "outlined", divider: "none" },
    motion: { preset: "fade-up", stagger: 0.04, y: 18 },
    fonts: { display: "Figtree", body: "Atkinson Hyperlegible", mono: "IBM Plex Mono", displayWeight: 700, headingWeight: 700, tracking: "-0.02em", leading: 1.08, label: "0.12em" },
    radius: "rounded-2xl",
    density: "normal",
    glow: false,
    heroTiers: [0, 1],
    palettes: [
      p("#F4FAFA", "#E4F1F2", "#0E2A2F", "#3F5C62", "#0B6E7A", "#B4411F"),
      p("#F4FAFA", "#E4F1F2", "#0E2A2F", "#3F5C62", "#1D5FA8", "#0B7A5B"),
      p("#F4FAFA", "#E4F1F2", "#0E2A2F", "#3F5C62", "#4B5FA3", "#0E7490"),
    ],
    match: { clusters: ["healthcare"], secondary: ["education"], emphasis: "credentials", personality: ["corporate", "academic"] },
  },
  {
    id: "chambers",
    name: "Chambers",
    tagline: "Ivory, ink and burgundy: measured and authoritative.",
    bestFor: ["Lawyers and paralegals", "Compliance and policy", "Government and public sector", "Consultants in regulated fields"],
    tones: ["formal", "calm"],
    mode: "light",
    layout: "single-column",
    direction: "EDITORIAL_MONO",
    hero: "editorial",
    heroSection: "statement",
    nav: "full-width-bar",
    bgType: "EDITORIAL_FLAT",
    order: ["hero", "about", "experience", "education", "certifications", "highlights", "skills", "projects", "contact"],
    variants: {
      about: "lead",
      skills: "inline",
      experience: "list",
      projects: "list",
      contact: "list",
      education: "list",
      highlights: "list",
      certifications: "list",
    },
    components: { card: "flat", button: "text-arrow", badge: "outlined", divider: "thick-ruled" },
    motion: { preset: "fade-up", stagger: 0.04, y: 18 },
    fonts: { display: "Newsreader", body: "Libre Franklin", mono: "IBM Plex Mono", displayWeight: 600, headingWeight: 600, tracking: "-0.02em", leading: 1.04, label: "0.2em" },
    radius: "rounded-none",
    density: "normal",
    glow: false,
    heroTiers: [0, 1],
    palettes: [
      p("#FAF7F2", "#F0EAE0", "#1A1714", "#5A524A", "#7A1F2B", "#8A6D1F"),
      p("#FAF7F2", "#F0EAE0", "#1A1714", "#5A524A", "#1F3A5F", "#8A6D1F"),
      p("#FAF7F2", "#F0EAE0", "#1A1714", "#5A524A", "#2D4A3A", "#7A1F2B"),
    ],
    match: { clusters: ["legal"], secondary: ["finance", "hr", "education"], personality: ["corporate", "academic"], emphasis: "credentials", seniority: ["senior", "lead", "executive"] },
  },
  {
    id: "people",
    name: "People First",
    tagline: "Warm coral and rounded forms for people-centred work.",
    bestFor: ["HR and talent partners", "Recruiters", "People operations", "Customer success and support"],
    tones: ["warm", "playful", "calm"],
    mode: "light",
    layout: "asymmetric",
    direction: "ORGANIC_GRADIENT",
    hero: "split-left",
    heroSection: "split",
    nav: "floating-pill",
    bgType: "EDITORIAL_FLAT",
    order: ["hero", "about", "highlights", "experience", "skills", "certifications", "education", "projects", "contact"],
    variants: {
      about: "columns",
      skills: "chips",
      experience: "cards",
      projects: "cards",
      contact: "card",
      education: "list",
      highlights: "figures",
      certifications: "list",
    },
    components: { card: "solid", button: "solid", badge: "pill-glass", divider: "none" },
    motion: { preset: "stagger-grid", stagger: 0.06, y: 30 },
    fonts: { display: "Red Hat Display", body: "Red Hat Text", mono: "DM Mono", displayWeight: 800, headingWeight: 700, tracking: "-0.03em", leading: 1.04, label: "0.16em" },
    radius: "rounded-3xl",
    density: "normal",
    glow: false,
    heroTiers: [1],
    palettes: [
      p("#FFF9F6", "#FCEEE6", "#2A1B22", "#6A5560", "#B02A5B", "#1F6F6A"),
      p("#FFF9F6", "#FCEEE6", "#2A1B22", "#6A5560", "#1F5FA8", "#C2410C"),
      p("#FFF9F6", "#FCEEE6", "#2A1B22", "#6A5560", "#0F766E", "#B02A5B"),
    ],
    match: { clusters: ["hr"], secondary: ["education", "sales", "marketing", "healthcare"], emphasis: "experience", personality: ["corporate"] },
  },
  {
    id: "closer",
    name: "Closer",
    tagline: "Confident navy and signal orange. Results first.",
    bestFor: ["Sales and account executives", "Business development", "Revenue operations", "Account managers"],
    tones: ["bold", "formal"],
    mode: "dark",
    layout: "asymmetric",
    direction: "LIQUID_ENTERPRISE",
    hero: "split-left",
    heroSection: "banner",
    nav: "full-width-bar",
    bgType: "ENTERPRISE_GRADIENT",
    order: ["hero", "highlights", "about", "experience", "skills", "certifications", "education", "projects", "contact"],
    variants: {
      about: "columns",
      skills: "chips",
      experience: "rows",
      projects: "list",
      contact: "statement",
      education: "list",
      highlights: "figures",
      certifications: "list",
    },
    components: { card: "solid", button: "solid", badge: "outlined", divider: "none" },
    motion: { preset: "slide-reveal", stagger: 0.05, y: 30 },
    fonts: { display: "Archivo", body: "Chivo", mono: "IBM Plex Mono", displayWeight: 800, headingWeight: 700, tracking: "-0.035em", leading: 1.0, label: "0.18em" },
    radius: "rounded-lg",
    density: "normal",
    glow: false,
    heroTiers: [1, 2],
    palettes: [
      p("#0B1626", "#12233A", "#EAF1FB", "#9DB2CC", "#FF9A4D", "#4DD2C0"),
      p("#0B1626", "#12233A", "#EAF1FB", "#9DB2CC", "#5EEAD4", "#FBBF24"),
      p("#0B1626", "#12233A", "#EAF1FB", "#9DB2CC", "#7CB4FF", "#FF9A4D"),
    ],
    match: { clusters: ["sales"], secondary: ["marketing", "finance", "hr"], emphasis: "experience", personality: ["corporate"] },
  },
  {
    id: "campaign",
    name: "Campaign",
    tagline: "Loud in the right places: pop colour and clear results.",
    bestFor: ["Marketers and brand managers", "Content and social leads", "Growth and SEO", "Communications and PR"],
    tones: ["bold", "playful"],
    mode: "light",
    layout: "asymmetric",
    direction: "ORGANIC_GRADIENT",
    hero: "split-left",
    heroSection: "banner",
    nav: "floating-pill",
    bgType: "EDITORIAL_FLAT",
    order: ["hero", "highlights", "projects", "experience", "about", "skills", "education", "certifications", "contact"],
    variants: {
      about: "lead",
      skills: "inline",
      experience: "rows",
      projects: "feature",
      contact: "footer",
      education: "list",
      highlights: "figures",
      certifications: "list",
    },
    components: { card: "bordered", button: "solid", badge: "pill-glass", divider: "none" },
    motion: { preset: "slide-reveal", stagger: 0.06, y: 36 },
    fonts: { display: "Epilogue", body: "Karla", mono: "DM Mono", displayWeight: 800, headingWeight: 700, tracking: "-0.04em", leading: 0.98, label: "0.18em" },
    radius: "rounded-2xl",
    density: "airy",
    glow: false,
    heroTiers: [1, 2],
    palettes: [
      p("#FFFAF5", "#FFE9DA", "#1B1220", "#5E4B63", "#D1124F", "#0F5F66"),
      p("#FFFAF5", "#FFE9DA", "#1B1220", "#5E4B63", "#B93A0B", "#1F4FD8"),
      p("#FFFAF5", "#FFE9DA", "#1B1220", "#5E4B63", "#0A56E8", "#C2410C"),
    ],
    match: { clusters: ["marketing"], secondary: ["creative", "design", "sales"], personality: ["creative"], emphasis: "projects", projectLed: true, needsRich: true },
  },
  {
    id: "kitchen",
    name: "Kitchen Table",
    tagline: "Terracotta, cream and a hint of herb. Appetising, not fussy.",
    bestFor: ["Chefs and cooks", "Bakers and pastry chefs", "Hospitality and events", "Food writers and stylists"],
    tones: ["warm", "playful"],
    mode: "light",
    layout: "magazine",
    direction: "ORGANIC_GRADIENT",
    hero: "split-left",
    heroSection: "split",
    nav: "floating-pill",
    bgType: "EDITORIAL_FLAT",
    order: ["hero", "about", "experience", "projects", "highlights", "skills", "certifications", "education", "contact"],
    variants: {
      about: "lead",
      skills: "inline",
      experience: "rows",
      projects: "gallery",
      contact: "card",
      education: "list",
      highlights: "list",
      certifications: "list",
    },
    components: { card: "solid", button: "solid", badge: "pill-glass", divider: "none" },
    motion: { preset: "parallax", stagger: 0.07, y: 32 },
    fonts: { display: "Vollkorn", body: "Mulish", mono: "DM Mono", displayWeight: 700, headingWeight: 700, tracking: "-0.02em", leading: 1.04, label: "0.18em" },
    radius: "rounded-2xl",
    density: "airy",
    glow: false,
    heroTiers: [1, 2],
    palettes: [
      p("#FBF5EC", "#F2E7D6", "#2B1D14", "#6B5645", "#A33B20", "#5A6B2A"),
      p("#FBF5EC", "#F2E7D6", "#2B1D14", "#6B5645", "#5A6B2A", "#A33B20"),
      p("#FBF5EC", "#F2E7D6", "#2B1D14", "#6B5645", "#7A2E3A", "#A16207"),
    ],
    match: { clusters: ["culinary"], secondary: ["creative", "hr"], emphasis: "experience", personality: ["creative"] },
  },
  {
    id: "workbench",
    name: "Workbench",
    tagline: "Hard edges, safety orange and a visible grid.",
    bestFor: ["Mechanical, civil and electrical engineers", "Manufacturing and quality", "Construction and project engineers", "Hardware and embedded"],
    tones: ["techy", "bold", "calm"],
    mode: "light",
    layout: "split-fixed",
    direction: "BRUTALIST_GRID",
    hero: "split-left",
    heroSection: "statement",
    nav: "side-rail",
    bgType: "BRUTALIST_RAW",
    order: ["hero", "about", "highlights", "projects", "experience", "certifications", "skills", "education", "contact"],
    variants: {
      about: "prose",
      skills: "columns",
      experience: "list",
      projects: "feature",
      contact: "list",
      education: "list",
      highlights: "figures",
      certifications: "grid",
    },
    components: { card: "brutalist", button: "brutalist", badge: "square-mono", divider: "thick-ruled" },
    motion: { preset: "magnetic", stagger: 0.04, y: 24 },
    fonts: { display: "Barlow Condensed", body: "Barlow", mono: "IBM Plex Mono", displayWeight: 700, headingWeight: 700, tracking: "-0.01em", leading: 1.0, label: "0.14em" },
    radius: "rounded-none",
    density: "normal",
    glow: false,
    heroTiers: [1, 2],
    palettes: [
      p("#F1F1EE", "#E3E3DE", "#151618", "#4F5258", "#A84300", "#1E40AF"),
      p("#F1F1EE", "#E3E3DE", "#151618", "#4F5258", "#1E40AF", "#A84300"),
      p("#F1F1EE", "#E3E3DE", "#151618", "#4F5258", "#0F5F5A", "#A84300"),
    ],
    match: { clusters: ["engineering"], secondary: ["software"], personality: ["technical"], emphasis: "projects", projectLed: true },
  },
  {
    id: "independent",
    name: "Independent",
    tagline: "Sand and deep teal: a personal brand with a point of view.",
    bestFor: ["Freelancers", "Consultants and advisors", "Solo practitioners", "Contractors and small studios"],
    tones: ["calm", "warm", "bold"],
    mode: "light",
    layout: "asymmetric",
    direction: "ORGANIC_GRADIENT",
    hero: "split-left",
    heroSection: "split",
    nav: "floating-pill",
    bgType: "EDITORIAL_FLAT",
    order: ["hero", "about", "projects", "highlights", "experience", "skills", "certifications", "education", "contact"],
    variants: {
      about: "columns",
      skills: "inline",
      experience: "rows",
      projects: "feature",
      contact: "statement",
      education: "list",
      highlights: "figures",
      certifications: "list",
    },
    components: { card: "bordered", button: "solid", badge: "outlined", divider: "none" },
    motion: { preset: "slide-reveal", stagger: 0.06, y: 32 },
    fonts: { display: "Familjen Grotesk", body: "Onest", mono: "DM Mono", displayWeight: 700, headingWeight: 700, tracking: "-0.035em", leading: 1.0, label: "0.18em" },
    radius: "rounded-2xl",
    density: "normal",
    glow: false,
    heroTiers: [1, 2],
    palettes: [
      p("#F6F1E9", "#ECE4D6", "#17211F", "#55625F", "#0F5E57", "#B4532A"),
      p("#F6F1E9", "#ECE4D6", "#17211F", "#55625F", "#8C3B1E", "#0F5E57"),
      p("#F6F1E9", "#ECE4D6", "#17211F", "#55625F", "#26457A", "#B4532A"),
    ],
    match: { clusters: ["freelance"], secondary: ["design", "marketing", "software", "creative"], stage: ["established", "expert"], emphasis: "projects", projectLed: true },
  },
  {
    id: "boardroom",
    name: "Boardroom",
    tagline: "Charcoal and brass: restrained, senior, impact-led.",
    bestFor: ["Executives and directors", "Founders and general managers", "VPs and heads of function", "Board and advisory roles"],
    tones: ["formal", "bold"],
    mode: "dark",
    layout: "single-column",
    direction: "LIQUID_ENTERPRISE",
    hero: "fullscreen-center",
    heroSection: "centered",
    nav: "full-width-bar",
    bgType: "ENTERPRISE_GRADIENT",
    order: ["hero", "highlights", "about", "experience", "education", "certifications", "skills", "projects", "contact"],
    variants: {
      about: "lead",
      skills: "columns",
      experience: "rows",
      projects: "list",
      contact: "statement",
      education: "list",
      highlights: "figures",
      certifications: "list",
    },
    components: { card: "solid", button: "solid", badge: "outlined", divider: "none" },
    motion: { preset: "fade-up", stagger: 0.04, y: 18 },
    fonts: { display: "Spectral", body: "Libre Franklin", mono: "IBM Plex Mono", displayWeight: 600, headingWeight: 600, tracking: "-0.02em", leading: 1.06, label: "0.2em" },
    radius: "rounded-lg",
    density: "airy",
    glow: false,
    heroTiers: [0, 1],
    palettes: [
      p("#121418", "#1A1D23", "#ECE8DF", "#A5A29A", "#CBA961", "#7FA3C7"),
      p("#121418", "#1A1D23", "#ECE8DF", "#A5A29A", "#A8C3D8", "#CBA961"),
      p("#0F1714", "#17221E", "#E8EEE9", "#9FB0A7", "#C9B27C", "#7FB69E"),
    ],
    match: { clusters: ["executive"], secondary: ["finance", "sales", "legal"], seniority: ["executive", "lead"], stage: ["expert"], emphasis: "experience", personality: ["corporate"] },
  },
  {
    id: "scholar",
    name: "Scholar",
    tagline: "Numbered sections, serif headlines, citation-friendly.",
    bestFor: ["Academics and professors", "PhD candidates and postdocs", "Research scientists", "Lab and policy researchers"],
    tones: ["calm", "formal"],
    mode: "light",
    layout: "single-column",
    direction: "EDITORIAL_MONO",
    hero: "editorial",
    heroSection: "statement",
    nav: "full-width-bar",
    bgType: "EDITORIAL_FLAT",
    order: ["hero", "about", "education", "projects", "experience", "certifications", "highlights", "skills", "contact"],
    variants: {
      about: "prose",
      skills: "inline",
      experience: "list",
      projects: "list",
      contact: "list",
      education: "list",
      highlights: "list",
      certifications: "list",
    },
    components: { card: "flat", button: "text-arrow", badge: "outlined", divider: "thick-ruled" },
    motion: { preset: "fade-up", stagger: 0.04, y: 18 },
    fonts: { display: "Crimson Pro", body: "Source Sans 3", mono: "IBM Plex Mono", displayWeight: 600, headingWeight: 600, tracking: "-0.015em", leading: 1.04, label: "0.2em" },
    radius: "rounded-none",
    density: "normal",
    glow: false,
    heroTiers: [1],
    palettes: [
      p("#FBFAF6", "#F0EEE6", "#1C1C24", "#53535F", "#243C8C", "#8C3B2E"),
      p("#FBFAF6", "#F0EEE6", "#1C1C24", "#53535F", "#6B2D5C", "#1F5F5B"),
      p("#FBFAF6", "#F0EEE6", "#1C1C24", "#53535F", "#1F5F5B", "#6B2D5C"),
    ],
    match: { clusters: ["academic"], secondary: ["education", "healthcare", "engineering"], personality: ["academic"], emphasis: "education" },
  },
  {
    id: "pivot",
    name: "Pivot",
    tagline: "Skills and projects first, so the next chapter reads clearly.",
    bestFor: ["Career changers", "Returners to work", "Self-taught talent", "Portfolio-over-pedigree profiles"],
    tones: ["warm", "playful", "calm"],
    mode: "light",
    layout: "asymmetric",
    direction: "LIQUID_ENTERPRISE",
    hero: "split-left",
    heroSection: "card",
    nav: "floating-pill",
    bgType: "EDITORIAL_FLAT",
    order: ["hero", "about", "skills", "projects", "experience", "education", "certifications", "highlights", "contact"],
    variants: {
      about: "lead",
      skills: "chips",
      experience: "timeline",
      projects: "cards",
      contact: "card",
      education: "list",
      highlights: "list",
      certifications: "list",
    },
    components: { card: "solid", button: "solid", badge: "pill-glass", divider: "none" },
    motion: { preset: "stagger-grid", stagger: 0.06, y: 30 },
    fonts: { display: "Lexend", body: "Figtree", mono: "Fira Code", displayWeight: 600, headingWeight: 600, tracking: "-0.035em", leading: 1.04, label: "0.16em" },
    radius: "rounded-2xl",
    density: "normal",
    glow: false,
    heroTiers: [1],
    palettes: [
      p("#F6F7F4", "#E9EDE6", "#16211C", "#505F57", "#1F6A55", "#B5470F"),
      p("#F6F7F4", "#E9EDE6", "#16211C", "#505F57", "#0D63C4", "#B5470F"),
      p("#F6F7F4", "#E9EDE6", "#16211C", "#505F57", "#8A3B2E", "#1F6A55"),
    ],
    match: { clusters: ["switcher"], stage: ["pivoting"], emphasis: "experience", projectLed: false },
  },
]
